// Copyright (c) Matt Liotta
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;

using DocumentFormat.OpenXml.Features.FormulaEvaluation.Compilation;

namespace DocumentFormat.OpenXml.Features.FormulaEvaluation.Functions;

/// <summary>
/// Registry for built-in Excel functions.
/// </summary>
public static class FunctionRegistry
{
    private static readonly Dictionary<string, IFunctionImplementation> _functions = new(StringComparer.OrdinalIgnoreCase)
    {
        // Phase 0 (3)
        { "SUM", SumFunction.Instance },
        { "AVERAGE", AverageFunction.Instance },
        { "IF", IfFunction.Instance },

        // Math (77)
        { "COUNT", CountFunction.Instance },
        { "COUNTA", CountAFunction.Instance },
        { "COUNTBLANK", CountBlankFunction.Instance },
        { "COUNTIF", CountIfFunction.Instance },
        { "COUNTIFS", CountIfsFunction.Instance },
        { "MAX", MaxFunction.Instance },
        { "MIN", MinFunction.Instance },
        { "ROUND", RoundFunction.Instance },
        { "ROUNDUP", RoundUpFunction.Instance },
        { "ROUNDDOWN", RoundDownFunction.Instance },
        { "ABS", AbsFunction.Instance },
        { "PRODUCT", ProductFunction.Instance },
        { "POWER", PowerFunction.Instance },
        { "SUMIF", SumIfFunction.Instance },
        { "SUMIFS", SumIfsFunction.Instance },
        { "SUMPRODUCT", SumProductFunction.Instance },
        { "SQRT", SqrtFunction.Instance },
        { "MOD", ModFunction.Instance },
        { "INT", IntFunction.Instance },
        { "CEILING", CeilingFunction.Instance },
        { "FLOOR", FloorFunction.Instance },
        { "TRUNC", TruncFunction.Instance },
        { "SIGN", SignFunction.Instance },
        { "EXP", ExpFunction.Instance },
        { "LN", LnFunction.Instance },
        { "LOG", LogFunction.Instance },
        { "LOG10", Log10Function.Instance },
        { "PI", PiFunction.Instance },
        { "RADIANS", RadiansFunction.Instance },
        { "DEGREES", DegreesFunction.Instance },
        { "SIN", SinFunction.Instance },
        { "COS", CosFunction.Instance },
        { "TAN", TanFunction.Instance },
        { "ASIN", AsinFunction.Instance },
        { "ACOS", AcosFunction.Instance },
        { "ATAN", AtanFunction.Instance },
        { "ATAN2", Atan2Function.Instance },
        { "SINH", SinhFunction.Instance },
        { "COSH", CoshFunction.Instance },
        { "TANH", TanhFunction.Instance },
        { "ASINH", AsinhFunction.Instance },
        { "ACOSH", AcoshFunction.Instance },
        { "ATANH", AtanhFunction.Instance },
        { "SEC", SecFunction.Instance },
        { "SECH", SechFunction.Instance },
        { "CSC", CscFunction.Instance },
        { "CSCH", CschFunction.Instance },
        { "COT", CotFunction.Instance },
        { "COTH", CothFunction.Instance },
        { "ACOT", AcotFunction.Instance },
        { "ACOTH", AcothFunction.Instance },
        { "RAND", RandFunction.Instance },
        { "RANDBETWEEN", RandBetweenFunction.Instance },
        { "RANDARRAY", RandArrayFunction.Instance },
        { "FACT", FactFunction.Instance },
        { "GCD", GcdFunction.Instance },
        { "LCM", LcmFunction.Instance },
        { "EVEN", EvenFunction.Instance },
        { "ODD", OddFunction.Instance },
        { "COMBIN", CombinFunction.Instance },
        { "PERMUT", PermutFunction.Instance },
        { "MROUND", MroundFunction.Instance },
        { "QUOTIENT", QuotientFunction.Instance },
        { "SUMSQ", SumSqFunction.Instance },
        { "SUMX2MY2", SumX2MY2Function.Instance },
        { "SUMX2PY2", SumX2PY2Function.Instance },
        { "SUMXMY2", SumXMY2Function.Instance },
        { "MULTINOMIAL", MultinomialFunction.Instance },
        { "SERIESSUM", SeriesSumFunction.Instance },
        { "BASE", BaseFunction.Instance },
        { "DECIMAL", DecimalFunction.Instance },
        { "ARABIC", ArabicFunction.Instance },
        { "ROMAN", RomanFunction.Instance },
        { "SQRTPI", SqrtPiFunction.Instance },

        // Logical (10)
        { "TRUE", TrueFunction.Instance },
        { "FALSE", FalseFunction.Instance },
        { "AND", AndFunction.Instance },
        { "OR", OrFunction.Instance },
        { "NOT", NotFunction.Instance },
        { "CHOOSE", ChooseFunction.Instance },
        { "IFS", IfsFunction.Instance },
        { "SWITCH", SwitchFunction.Instance },
        { "XOR", XorFunction.Instance },
        { "IFNA", IfnaFunction.Instance },

        // Text (44)
        { "CONCATENATE", ConcatenateFunction.Instance },
        { "CONCAT", ConcatFunction.Instance },
        { "TEXTJOIN", TextJoinFunction.Instance },
        { "LEFT", LeftFunction.Instance },
        { "RIGHT", RightFunction.Instance },
        { "MID", MidFunction.Instance },
        { "LEN", LenFunction.Instance },
        { "TRIM", TrimFunction.Instance },
        { "TRIMALL", TrimAllFunction.Instance },
        { "UPPER", UpperFunction.Instance },
        { "LOWER", LowerFunction.Instance },
        { "PROPER", ProperFunction.Instance },
        { "TEXT", TextFunction.Instance },
        { "VALUE", ValueFunction.Instance },
        { "FIND", FindFunction.Instance },
        { "SEARCH", SearchFunction.Instance },
        { "SUBSTITUTE", SubstituteFunction.Instance },
        { "REPLACE", ReplaceFunction.Instance },
        { "REPT", ReptFunction.Instance },
        { "EXACT", ExactFunction.Instance },
        { "CHAR", CharFunction.Instance },
        { "CODE", CodeFunction.Instance },
        { "UNICHAR", UnicharFunction.Instance },
        { "UNICODE", UnicodeFunction.Instance },
        { "CLEAN", CleanFunction.Instance },
        { "T", TFunction.Instance },
        { "REVERSE", ReverseFunction.Instance },
        { "FIXED", FixedFunction.Instance },
        { "DOLLAR", DollarFunction.Instance },
        { "NUMBERVALUE", NumberValueFunction.Instance },
        { "PHONETIC", PhoneticFunction.Instance },
        { "TEXTBEFORE", TextBeforeFunction.Instance },
        { "TEXTAFTER", TextAfterFunction.Instance },
        { "TEXTSPLIT", TextSplitFunction.Instance },
        { "VALUETOTEXT", ValueToTextFunction.Instance },
        { "ARRAYTOTEXT", ArrayToTextFunction.Instance },
        { "LENB", LenBFunction.Instance },
        { "LEFTB", LeftBFunction.Instance },
        { "RIGHTB", RightBFunction.Instance },
        { "MIDB", MidBFunction.Instance },
        { "FINDB", FindBFunction.Instance },
        { "SEARCHB", SearchBFunction.Instance },
        { "REPLACEB", ReplaceBFunction.Instance },

        // Lookup (19)
        { "VLOOKUP", VLookupFunction.Instance },
        { "HLOOKUP", HLookupFunction.Instance },
        { "INDEX", IndexFunction.Instance },
        { "MATCH", MatchFunction.Instance },
        { "XLOOKUP", XLookupFunction.Instance },
        { "XMATCH", XMatchFunction.Instance },
        { "COLUMN", ColumnFunction.Instance },
        { "ROW", RowFunction.Instance },
        { "COLUMNS", ColumnsFunction.Instance },
        { "ROWS", RowsFunction.Instance },
        { "ADDRESS", AddressFunction.Instance },
        { "OFFSET", OffsetFunction.Instance },
        { "INDIRECT", IndirectFunction.Instance },
        { "FORMULATEXT", FormulaTextFunction.Instance },
        { "ISFORMULA", IsFormulaFunction.Instance },
        { "SHEET", SheetFunction.Instance },
        { "SHEETS", SheetsFunction.Instance },
        { "GETPIVOTDATA", GetPivotDataFunction.Instance },
        { "HYPERLINK", HyperlinkFunction.Instance },

        // Array (17)
        { "TRANSPOSE", TransposeFunction.Instance },
        { "SORT", SortFunction.Instance },
        { "SORTBY", SortByFunction.Instance },
        { "FILTER", FilterFunction.Instance },
        { "UNIQUE", UniqueFunction.Instance },
        { "SEQUENCE", SequenceFunction.Instance },
        { "TAKE", TakeFunction.Instance },
        { "DROP", DropFunction.Instance },
        { "CHOOSECOLS", ChooseColsFunction.Instance },
        { "CHOOSEROWS", ChooseRowsFunction.Instance },
        { "EXPAND", ExpandFunction.Instance },
        { "WRAPCOLS", WrapColsFunction.Instance },
        { "WRAPROWS", WrapRowsFunction.Instance },
        { "TOCOL", ToColFunction.Instance },
        { "TOROW", ToRowFunction.Instance },
        { "VSTACK", VStackFunction.Instance },
        { "HSTACK", HStackFunction.Instance },

        // Web (3)
        { "ENCODEURL", EncodeUrlFunction.Instance },
        { "WEBSERVICE", WebServiceFunction.Instance },
        { "FILTERXML", FilterXmlFunction.Instance },

        // Date/Time (25)
        { "TODAY", TodayFunction.Instance },
        { "NOW", NowFunction.Instance },
        { "DATE", DateFunction.Instance },
        { "YEAR", YearFunction.Instance },
        { "MONTH", MonthFunction.Instance },
        { "DAY", DayFunction.Instance },
        { "HOUR", HourFunction.Instance },
        { "MINUTE", MinuteFunction.Instance },
        { "SECOND", SecondFunction.Instance },
        { "WEEKDAY", WeekdayFunction.Instance },
        { "WEEKNUM", WeeknumFunction.Instance },
        { "ISOWEEKNUM", IsoweeknumFunction.Instance },
        { "DAYS", DaysFunction.Instance },
        { "TIME", TimeFunction.Instance },
        { "TIMEVALUE", TimeValueFunction.Instance },
        { "DATEVALUE", DateValueFunction.Instance },
        { "DAYS360", Days360Function.Instance },
        { "EOMONTH", EomonthFunction.Instance },
        { "EDATE", EdateFunction.Instance },
        { "NETWORKDAYS", NetworkdaysFunction.Instance },
        { "NETWORKDAYS.INTL", NetworkdaysIntlFunction.Instance },
        { "WORKDAY", WorkdayFunction.Instance },
        { "WORKDAY.INTL", WorkdayIntlFunction.Instance },
        { "YEARFRAC", YearfracFunction.Instance },
        { "DATEDIF", DatedifFunction.Instance },

        // Statistical (78)
        { "MEDIAN", MedianFunction.Instance },
        { "MODE", ModeFunction.Instance },
        { "MODE.SNGL", ModeSnglFunction.Instance },
        { "MODE.MULT", ModeMultFunction.Instance },
        { "STDEV", StDevFunction.Instance },
        { "STDEV.S", StDevSFunction.Instance },
        { "STDEV.P", StDevPFunction2.Instance },
        { "VAR", VarFunction.Instance },
        { "VAR.S", VarSFunction.Instance },
        { "VAR.P", VarPFunction2.Instance },
        { "RANK", RankFunction.Instance },
        { "AVERAGEIF", AverageIfFunction.Instance },
        { "AVERAGEIFS", AverageIfsFunction.Instance },
        { "MAXIFS", MaxIfsFunction.Instance },
        { "MINIFS", MinIfsFunction.Instance },
        { "STDEVP", StDevPFunction.Instance },
        { "VARP", VarPFunction.Instance },
        { "LARGE", LargeFunction.Instance },
        { "SMALL", SmallFunction.Instance },
        { "PERCENTILE", PercentileFunction.Instance },
        { "PERCENTILE.INC", PercentileIncFunction.Instance },
        { "PERCENTILE.EXC", PercentileExcFunction.Instance },
        { "QUARTILE", QuartileFunction.Instance },
        { "QUARTILE.INC", QuartileIncFunction.Instance },
        { "QUARTILE.EXC", QuartileExcFunction.Instance },
        { "CORREL", CorrelFunction.Instance },
        { "COVARIANCE.P", CovariancePFunction.Instance },
        { "COVARIANCE.S", CovarianceSFunction.Instance },
        { "SLOPE", SlopeFunction.Instance },
        { "INTERCEPT", InterceptFunction.Instance },
        { "FORECAST", ForecastFunction.Instance },
        { "FORECAST.LINEAR", ForecastLinearFunction.Instance },
        { "TREND", TrendFunction.Instance },
        { "GROWTH", GrowthFunction.Instance },
        { "LINEST", LinestFunction.Instance },
        { "LOGEST", LogestFunction.Instance },
        { "SKEW", SkewFunction.Instance },
        { "KURT", KurtFunction.Instance },
        { "FREQUENCY", FrequencyFunction.Instance },
        { "AVERAGEA", AverageAFunction.Instance },
        { "MINA", MinAFunction.Instance },
        { "MAXA", MaxAFunction.Instance },
        { "STDEVA", StDevAFunction.Instance },
        { "STDEVPA", StDevPAFunction.Instance },
        { "VARA", VarAFunction.Instance },
        { "VARPA", VarPAFunction.Instance },
        { "SUBTOTAL", SubtotalFunction.Instance },
        { "AGGREGATE", AggregateFunction.Instance },
        { "NORM.DIST", NormDistFunction.Instance },
        { "NORM.INV", NormInvFunction.Instance },
        { "NORM.S.DIST", NormSDistFunction.Instance },
        { "NORM.S.INV", NormSInvFunction.Instance },
        { "CONFIDENCE", ConfidenceFunction.Instance },
        { "CONFIDENCE.NORM", ConfidenceNormFunction.Instance },
        { "CONFIDENCE.T", ConfidenceTFunction.Instance },
        { "T.DIST", TDistFunction.Instance },
        { "T.DIST.RT", TDistRTFunction.Instance },
        { "T.DIST.2T", TDist2TFunction.Instance },
        { "T.INV", TInvFunction.Instance },
        { "T.INV.2T", TInv2TFunction.Instance },
        { "TDIST", TDistLegacyFunction.Instance },
        { "TINV", TInvLegacyFunction.Instance },
        { "CHISQ.DIST", ChiSqDistFunction.Instance },
        { "CHISQ.DIST.RT", ChiSqDistRTFunction.Instance },
        { "CHISQ.INV", ChiSqInvFunction.Instance },
        { "CHISQ.INV.RT", ChiSqInvRTFunction.Instance },
        { "CHISQ.TEST", ChiSqTestFunction.Instance },
        { "F.DIST", FDistFunction.Instance },
        { "F.DIST.RT", FDistRTFunction.Instance },
        { "F.INV", FInvFunction.Instance },
        { "F.INV.RT", FInvRTFunction.Instance },
        { "BETA.DIST", BetaDistFunction.Instance },
        { "BETA.INV", BetaInvFunction.Instance },
        { "LOGNORM.DIST", LogNormDistFunction.Instance },
        { "LOGNORM.INV", LogNormInvFunction.Instance },

        // Information (20)
        { "ISNUMBER", IsNumberFunction.Instance },
        { "ISTEXT", IsTextFunction.Instance },
        { "IFERROR", IFErrorFunction.Instance },
        { "ISERROR", IsErrorFunction.Instance },
        { "ISNA", IsNaFunction.Instance },
        { "ISERR", IsErrFunction.Instance },
        { "ISBLANK", IsBlankFunction.Instance },
        { "ISEVEN", IsEvenFunction.Instance },
        { "ISODD", IsOddFunction.Instance },
        { "ISLOGICAL", IsLogicalFunction.Instance },
        { "ISNONTEXT", IsNonTextFunction.Instance },
        { "ISREF", IsRefFunction.Instance },
        { "ISOMITTED", IsOmittedFunction.Instance },
        { "TYPE", TypeFunction.Instance },
        { "ERROR.TYPE", ErrorTypeFunction.Instance },
        { "N", NFunction.Instance },
        { "NA", NaFunction.Instance },
        { "CELL", CellFunction.Instance },
        { "INFO", InfoFunction.Instance },
        { "AREAS", AreasFunction.Instance },

        // Financial (37)
        { "PMT", PmtFunction.Instance },
        { "FV", FvFunction.Instance },
        { "PV", PvFunction.Instance },
        { "NPER", NperFunction.Instance },
        { "RATE", RateFunction.Instance },
        { "NPV", NpvFunction.Instance },
        { "IRR", IrrFunction.Instance },
        { "IPMT", IpmtFunction.Instance },
        { "PPMT", PpmtFunction.Instance },
        { "SLN", SlnFunction.Instance },
        { "DB", DbFunction.Instance },
        { "DDB", DdbFunction.Instance },
        { "SYD", SydFunction.Instance },
        { "XNPV", XnpvFunction.Instance },
        { "XIRR", XirrFunction.Instance },
        { "MIRR", MirrFunction.Instance },
        { "FVSCHEDULE", FvscheduleFunction.Instance },
        { "CUMIPMT", CumipmtFunction.Instance },
        { "CUMPRINC", CumprincFunction.Instance },
        { "EFFECT", EffectFunction.Instance },
        { "NOMINAL", NominalFunction.Instance },
        { "PRICE", PriceFunction.Instance },
        { "YIELD", YieldFunction.Instance },
        { "DURATION", DurationFunction.Instance },
        { "MDURATION", MdurationFunction.Instance },
        { "PRICEDISC", PricediscFunction.Instance },
        { "YIELDDISC", YielddiscFunction.Instance },
        { "PRICEMAT", PricematFunction.Instance },
        { "YIELDMAT", YieldmatFunction.Instance },
        { "COUPDAYBS", CoupdaybsFunction.Instance },
        { "COUPDAYS", CoupdaysFunction.Instance },
        { "COUPDAYSNC", CoupdaysncFunction.Instance },
        { "COUPNCD", CoupncdFunction.Instance },
        { "COUPNUM", CoupnumFunction.Instance },
        { "COUPPCD", CouppcdFunction.Instance },
        { "DOLLARDE", DollardeFunction.Instance },
        { "DOLLARFR", DollarfrFunction.Instance },

        // Database (12)
        { "DSUM", DSumFunction.Instance },
        { "DCOUNT", DCountFunction.Instance },
        { "DCOUNTA", DCountAFunction.Instance },
        { "DAVERAGE", DAverageFunction.Instance },
        { "DMAX", DMaxFunction.Instance },
        { "DMIN", DMinFunction.Instance },
        { "DGET", DGetFunction.Instance },
        { "DPRODUCT", DProductFunction.Instance },
        { "DSTDEV", DStDevFunction.Instance },
        { "DSTDEVP", DStDevPFunction.Instance },
        { "DVAR", DVarFunction.Instance },
        { "DVARP", DVarPFunction.Instance },

        // Engineering (32)
        { "CONVERT", ConvertFunction.Instance },
        { "HEX2DEC", Hex2DecFunction.Instance },
        { "DEC2HEX", Dec2HexFunction.Instance },
        { "BIN2DEC", Bin2DecFunction.Instance },
        { "DEC2BIN", Dec2BinFunction.Instance },
        { "OCT2DEC", Oct2DecFunction.Instance },
        { "DEC2OCT", Dec2OctFunction.Instance },
        { "COMPLEX", ComplexFunction.Instance },
        { "IMREAL", ImRealFunction.Instance },
        { "IMAGINARY", ImaginaryFunction.Instance },
        { "IMABS", ImAbsFunction.Instance },
        { "IMARGUMENT", ImArgumentFunction.Instance },
        { "IMCONJUGATE", ImConjugateFunction.Instance },
        { "IMSUM", ImSumFunction.Instance },
        { "IMSUB", ImSubFunction.Instance },
        { "IMPRODUCT", ImProductFunction.Instance },
        { "IMDIV", ImDivFunction.Instance },
        { "IMPOWER", ImPowerFunction.Instance },
        { "IMSQRT", ImSqrtFunction.Instance },
        { "IMEXP", ImExpFunction.Instance },
        { "IMLN", ImLnFunction.Instance },
        { "IMLOG10", ImLog10Function.Instance },
        { "IMLOG2", ImLog2Function.Instance },
        { "IMSIN", ImSinFunction.Instance },
        { "IMCOS", ImCosFunction.Instance },
        { "IMTAN", ImTanFunction.Instance },
        { "IMSEC", ImSecFunction.Instance },
        { "IMCSC", ImCscFunction.Instance },
        { "IMCOT", ImCotFunction.Instance },
        { "IMSINH", ImSinhFunction.Instance },
        { "IMCOSH", ImCoshFunction.Instance },
        { "BITAND", BitAndFunction.Instance },
        { "BITOR", BitOrFunction.Instance },
        { "BITXOR", BitXorFunction.Instance },
        { "BITLSHIFT", BitLShiftFunction.Instance },
        { "BITRSHIFT", BitRShiftFunction.Instance },
    };

    /// <summary>
    /// Gets a function by name.
    /// </summary>
    /// <param name="name">The function name.</param>
    /// <param name="function">The function implementation.</param>
    /// <returns>True if the function was found.</returns>
    public static bool TryGetFunction(string name, out IFunctionImplementation? function)
    {
        return _functions.TryGetValue(name, out function);
    }
}
